name: devchoice
description: a new tech-related podcast recommendation every Tuesday and Thursday
author: Yves Gurcan

feed:
  updatePeriod: daily #can be hourly, daily, weekly, monthly, yearly
  updateFrequency: 1 #this number goes with updatePeriod (for example: 'weekly' and '2' means that the podcast is updated every other week)
  explicit: no #can be yes, no, clean
  logo: https://devchoice.yvesgurcan.com/assets/images/devchoice.png #expects a URL
  

collections:
  podcasts:
    output: true
  images:
    output: true
  
